# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True, db_column='UserID', null=True)),
                ('username', models.CharField(blank=True, db_column='UserName', max_length=1000, null=True)),
            ],
        ),
    ]
